#!/bin/bash

lvim () {
  if [[ "$1" = /* ]]; then
    file_name="$(basename ${1})"
    dir_name="$(dirname ${1})"
  else
    file_name="$1"
    dir_name="$(pwd)"
  fi
  
  # CMD="/bin/bash -lc 'cd /root/workspace && lvim $file_name'"
  docker run --rm -v "$dir_name":/root/workspace -it thedeveloper/lvim:latest "$file_name"
}